name: Tailwind CSS Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Pobierz pliki z repozytorium
        uses: actions/checkout@v4

      - name: Przygotuj srodowisko Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Zainstaluj i skompiluj Tailwinda
        run: |
          npm init -y
          npm install tailwindcss@3
          npx tailwindcss -i ./input.css -o ./style.css --minify

      - name: Wrzuc wygenerowany style.css na GitHuba
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automatyczna kompilacja style.css"
          file_pattern: "style.css"
