name: Zbuduj i Opublikuj (Tailwind + GH Pages)

on:
  push:
    branches: ["main"] # Zmień na "master", jeśli Twoja główna gałąź to master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu repozytorium
        uses: actions/checkout@v4

      - name: Instalacja środowiska Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Kompilacja Tailwind CSS
        # To ta sama komenda, którą wpisałbyś na swoim komputerze
        run: npx -y tailwindcss@latest -i ./input.css -o ./style.css --minify

      - name: Konfiguracja GitHub Pages
        uses: actions/configure-pages@v4

      - name: Spakowanie gotowej strony
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Wrzuca cały folder z wygenerowanym style.css

      - name: Publikacja na GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
